### ISSUE TITLE
Let's talk about how to support version guards/flags.

### ISSUE THREAD

**Issue by theSteveMitchell** [ejholmes/restforce#179]
#178 #177 #172 #153 All add new features that aren't available in api version 26.0, and use different strategy to check api version

@paulnunnerley @zenchild 
Can we talk about:

- [x] Should we change the default version? (26 is pretty old!) [solved - default to v33]
- [x] Standardizing the version check (I like @zenchild 's approach)
- [x] Standardize the error for failed version check
- [x] Version support for Travis CI - [solved.  Move 1.9.3 and 1.8 to allow_failures section]

**Comment by zenchild** [comment]
### Default Version
I'm in favor of updating the default version. At the moment **"29.0"** seems to be a good least-common-denominator. On a side-note, I have some uncommitted code for **api.rb** that will query the available versions.

### Version check
I like the version guard that yields the block. That makes error handling consistent for all versioning errors and you don't have a lot of begin/rescue statements scattered throughout your code.

### Standardize error
This I don't really have an opinion about. @theSteveMitchell I completely missed the error you added in #153 or I would have named APIVersionError the same.

### Addendum: Ruby Version Support
I don't know if we want to add to this topic, but when do you guys think Ruby 1.8.x support should go? I'm in the habit of using the new Hash syntax and I always forget when I add patches that Restforce still supports 1.8.x. Inevitably, the Travis build fails. If someone is passionate about keeping 1.8 support I'll suck it up but I'd love to see it killed off. Ideally the same would stand for 1.9 but I'll step back from the ledge on that one for now.

Finally, I'll yield all final opinions to @ejholmes since he is the maintainer.

Cheers  -- Dan

CC: @daveespo  I'm adding you to the conversation in case you have anything to add.

**Comment by theSteveMitchell** [comment]
@zenchild I added ruby version support also in the task list.  I Pretty much agree with you.  It looks like 29.0 came out in October 2013, so probably safe to change the default.  As far as ruby versions, I would support dropping 1.8 for sure.  For 1.9, maybe we can add an allow_failures section to travis so that users of 1.9 can still see the build status, but it won't block PRs.

**Comment by paulnunnerley** [comment]
+1 for version check ala @zenchild 

29 seems a reasonable place to take the version defalt, we've been running against v29 of the API for a few months in production with no issues.

I agree with @theSteveMitchell on the subject of 1.8 support. I don't care about supporting 1.8 but providing visibility of the build status against 1.8 should be valuable to people who do. This gives people the opportunity to fix broken compatibility if they require it.

**Comment by daveespo** [comment]
I'll be the devil's advocate here: 
 * Why not have the default be v33? Changing the default version could be a breaking change for some apps (i.e. all of a sudden new fields start appearing when retrieving SObjects (ex. Contact.LastViewedDate), and new standard SObjects are available too). So if this change to the default version is going out, why not shoot straight to v33? The only reason to pick v29 would be if there is a significant semantic change to an existing REST resource between v29 and v30+. I'm not aware of any.
 * As for trying to embody the API availability of particular resources in Restforce code -- why bother? It will be an inconsistently implemented pattern -- that is, you will receive a 'INVALID_TYPE: sObject type 'XYZ' is not supported.' error when trying to query against an object that's not available in the API version you've connected with -- versus other API methods returning the Restforce::ApiVersionError (per #178). If the default API version always supports all of the methods implemented within Resforce (query_all, limits, etc.), then only someone that knows what they're doing and intentionally downgrades to a prior API version would be affected -- and they would expect 404/Not Found (or whatever the error is when accessing the resource that's not available in that API version)

And yeah, I think retiring Ruby 1.8 support is overdue :-)

**Comment by zenchild** [comment]
I'd be in favor of v33. I'm not all that worried about breaking apps. If there is potential for that it can be signified in the version. It's still backward compatible (unless Ruby 1.8 is thrown out) so a MINOR version increment should suffice as a warning.

I'm also fine to ditch the version_guard specific error but perhaps keeping the guard and emitting a warning that the version is not supported for the method. The reason for this would be because the methods that use it are concrete methods in the Restforce code and not just a call-out to `api_get`. Without the warning I can see the issues coming in already about, "Why doesn't such and such method work...." The version_guard method would become something like this:

```ruby
def version_guard(version, &block)
  begin
    yield
  rescue Faraday::ResourceNotFound => e
    if version.to_f > options[:api_version].to_f
      warn "You must have an api_version of at least #{version} to use this feature."
    end
    raise
  end
end
```

**Comment by theSteveMitchell** [comment]
+1 for v33 by default.  

I would prefer to keep the version_guard and the Restforce::ApiVersionError.  For 2 reasons:
1. The errors that come back from Salesforce can be quite obscure.  I think it's very likely someone down the road will try to access e.g. query_all, not understanding they have set the api_version to an incompatible one.  Also, imagine an ideal world where Salesforce might remove support for a deprecated method in the future.
2. It seems likely that a client app would want to be able to handle ApiVersionError differently from the 120 other possible Faraday errors that come back from Salesforce.  For a real example, I know of a SF sandbox environment that is a few versions behind their production instance.  

Sounds like we have consensus on the "default version" and "Travis" topics, so I'll update those above.

**Comment by theSteveMitchell** [comment]
@ejholmes Any thoughts?

**Comment by timrogers** [comment]
I'm a fan of the `version_guard` approach, so let's go for that. Makes it easy to standardise handling this problem. I'm also happy to jump to API version 33 by default, and would like to include this as part of 2.1 - we already need to bump since I'm going to change `PROXY_URI` to `SALESFORCE_PROXY_URI`.

I'd like to see @zenchild draft a readme for #178 and then we can get that merged, and then the other PRs which depend on that approach to versions.

/cc @theSteveMitchell @daveespo @paulnunnerley

**Comment by theSteveMitchell** [comment]
I think we've wrapped this up.  Thanks all!
