### ISSUE TITLE
Escaping apostrophies in query

### ISSUE THREAD

**Issue by alexiidx** [ejholmes/restforce#314]
I am having issues running a query on a company field where the name may have an apostrophe. I've tried to run gsub on the string but Faraday keeps running something strange in an infinite loop and I have to shut down the development server. I've also tried to hardcode an escaped apostrophe into the query but it doesn't fix it.

Is there a way to solve this?

**Comment by timrogers** [comment]
Can you provide a minimal test case which triggers this problem? (i.e. some
code I could run which triggers this problem)

**Comment by alexiidx** [comment]
This is my query:
client.query(
          "SELECT Id FROM Lead WHERE (Email = '#{row[6]}' OR
           (Company = '#{row[0]}' AND FirstName = '#{row[1]}' AND LastName = '#{row[2]}'))"
        )

row[0] would be a string like l'eixample
I've tried to do row[0] = row[0].gsub(/[']/,"\\\\'") to replace the apostrophe but it ends up in an infinite loop when I do this.

If you need anymore information, let me know.

**Comment by timrogers** [comment]
Could you provide an example value for "row" which causes the problem too?
I'd like to be able to try it locally.

**Comment by alexiidx** [comment]
row = ["L'Eixample Company", "First Name", "Last Name", "123", "456", "Barcelona", "email@gmail.com"]

**Comment by timrogers** [comment]
I'm afraid I haven't been able to reproduce this - if I run the code above, it does fail, but with a `Faraday::ClientError`, since Salesforce responds with a 400 since Salesforce returns a `MALFORMED_QUERY` error.

If I then mutate `row[0]` with `row[0].gsub(/[']/,"\\\\'")`, the query runs successfully, and I get an empty collection back (since I have no matching records).

I'm happy to investigate this further and would love to fix your issue, but I'm not able to reproduce the loop you're experience. Can you double-check you've provided all the context I'd need to reproduce?

**Comment by alexiidx** [comment]
For context: I am looping over rows of a spreadsheet to upload leads into Salesforce. I am using the query to check duplicates within Salesforce. I'm really puzzled why it results in an endless loop when I mutate row[0].

**Comment by timrogers** [comment]
Have you tried stripping it back and experimenting to find exactly what
causes the loop? And maybe trying it in a vanilla Ruby script without other
dependencies? I'd love to get to the bottom of your issue.

**Comment by alexiidx** [comment]
I tried this on a single lead. It seems that whenever I escape the apostrophe, it starts looping over that one record plus about 99 blank records. I'm guessing it might be a formatting issue on the Salesforce side.
